global using System.Reflection;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.EntityFrameworkCore;
global using AutoMapper;
global using Infrastructure.SqliteDb;
global using CoreBusiness.Models;
global using Application.Dtos;
global using Application.Interfaces;