// <auto-generated />
using System;
using Infrastructure.SqlDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoreBusiness.Models.Archievement", b =>
                {
                    b.Property<int>("ArchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchievementId"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArchievementId");

                    b.ToTable("Archievements");

                    b.HasData(
                        new
                        {
                            ArchievementId = 1,
                            Count = 111,
                            Name = "Happy Clients"
                        },
                        new
                        {
                            ArchievementId = 2,
                            Count = 333,
                            Name = "Projects Finished"
                        },
                        new
                        {
                            ArchievementId = 4,
                            Count = 555,
                            Name = "Certificates Archieved"
                        },
                        new
                        {
                            ArchievementId = 3,
                            Count = 777,
                            Name = "Awards Won"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"), 1L, 1);

                    b.Property<string>("ImageGuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewImageBase64Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewImageExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativeImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            ImageGuid = "027c05a6-30ce-4126-a242-20aaa4fdaf71",
                            NewImageBase64Content = "",
                            NewImageExtension = ".png",
                            OldImagePath = "",
                            RelativeImagePath = ""
                        },
                        new
                        {
                            ImageId = 2,
                            ImageGuid = "cf079d42-1395-464e-acbc-d2ba8245d4cd",
                            NewImageBase64Content = "",
                            NewImageExtension = ".png",
                            OldImagePath = "",
                            RelativeImagePath = ""
                        },
                        new
                        {
                            ImageId = 3,
                            ImageGuid = "5ef17d87-5530-4251-80d5-5f64f89bb492",
                            NewImageBase64Content = "",
                            NewImageExtension = ".png",
                            OldImagePath = "",
                            RelativeImagePath = ""
                        });
                });

            modelBuilder.Entity("CoreBusiness.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "Content 1",
                            Excerpt = "Excerpt 1",
                            IsPublished = true,
                            PublishDate = new DateTime(2022, 2, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            ThumbnailPath = "",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "Content 2",
                            Excerpt = "Excerpt 2",
                            IsPublished = true,
                            PublishDate = new DateTime(2022, 2, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            ThumbnailPath = "",
                            Title = "Post 2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "Content 3",
                            Excerpt = "Excerpt 3",
                            IsPublished = true,
                            PublishDate = new DateTime(2022, 2, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            ThumbnailPath = "",
                            Title = "Post 3"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SvgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Description = "Building web apps with DotNet",
                            Name = "Web Developement",
                            SvgPath = "uploads/code.svg"
                        },
                        new
                        {
                            ServiceId = 2,
                            Description = "Upscaling apps using DevOps stacks",
                            Name = "DevOps",
                            SvgPath = "uploads/telegram.svg"
                        },
                        new
                        {
                            ServiceId = 3,
                            Description = "Visualizing data by Power Bi",
                            Name = "Data Analysist",
                            SvgPath = "uploads/creativity.svg"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Study")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "HCM City, Viet Nam",
                            AvatarImagePath = "uploads/avatar.jpg",
                            BackgroundImagePath = "uploads/ocean_background.jpg",
                            Degree = "Bachelor of Computer Science",
                            DoB = new DateTime(1998, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "huynguyen260398@gmail.com",
                            FirstName = "Huy",
                            Interests = "Building websites",
                            Intro = "I am a Web Developer, and I'm very passionate and dedicated to my work. With 2 years experience as a senior Web developer, I have acquired the skills and knowledge necessary to make your project a success.",
                            LastName = "Nguyen",
                            Phone = "(+84)903336493",
                            Study = "University of Greenwich"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
