global using AutoMapper;
global using API.Configs;
global using API.Controllers;
global using API.Interfaces;
global using CoreBusiness.Models;
global using Application.Dtos;
global using Application.Interfaces;
global using Application.Profiles;
global using Infrastructure.InMemDb;